GetEcmInfo.py: Don't open ECM_INFO file as bytes
Fix crash when service is encrypted.

File "/usr/lib/enigma2/python/Tools/GetEcmInfo.py", line 39, in pollEcmData
    d = line.split(':', 1)
TypeError: a bytes-like object is required, not 'str'
<   498.5254> 12:01:51.5254 [ePyObject] (CallObject(<bound method Poll.poll of
 <class 'Components.Converter.CryptoInfo.CryptoInfo'>(VerboseInfo)>,()) failed)